### ISSUE TITLE
code question in train.py

### ISSUE THREAD

**Issue by AMANKB** [DSKSD/RNN-for-Joint-NLU#1]
Hi,thank you for implementing the code for that paper. But I encountered a problem while  
``` python
 tag_score, intent_score = decoder(start_decode,hidden_c,output,x_mask)

> Traceback (most recent call last):
  File "E:/NER/RNN-for-Joint-NLU-master/train.py", line 102, in <module>
    train(config)
  File "E:/NER/RNN-for-Joint-NLU-master/train.py", line 54, in train
    tag_score, intent_score = decoder(start_decode,hidden_c,output,x_mask)
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\NER\RNN-for-Joint-NLU-master\model.py", line 120, in forward
    _, hidden = self.lstm(torch.cat((embedded,context,aligned),2), hidden) # input, context, aligned encoder hidden, hidden
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 175, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 152, in check_forward_args
    'Expected hidden[0] size {}, got {}')
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 148, in check_hidden_size
    raise RuntimeError(msg.format(expected_hidden_size, tuple(hx.size())))
RuntimeError: Expected hidden[0] size (1, 16, 128), got (2, 16, 128)

**Comment by harukaza** [comment]
hello,I also meet the problem. How do you solve it? Thank you very much. @AMANKB

**Comment by maggieezzat** [comment]
@AMANKB Could you please tell how did you solve this problem?
